services:
  db:
    image: "mariadb:11"
    restart: always
    ports:
      - '3306:3306'
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: kaamelott-gif
    volumes:
      - db-volume:/var/lib/mysql
volumes:
  db-volume: