openapi: "3.0.3"
info:
  title: "kaamelott_gif API"
  description: "kaamelott_gif API"
  version: "1.0.0"
servers:
- url: "https://kaamelott_gif"
paths:
  /:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "GIF API/APP"
  /api/gif/{file}:
    get:
      description: ""
      parameters:
      - name: "file"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "OK <br> A file response"
          content:
            application/*:
              schema:
                type: "object"
                format: "binary"
components:
  schemas:
    Response:
      type: "object"
      properties:
        code:
          type: "integer"
          format: "int32"
        message:
          type: "string"
      required:
      - "message"
    Response_String:
      type: "object"
      properties:
        code:
          type: "integer"
          format: "int32"
        message:
          type: "string"
        data:
          type: "string"