ktor:
  development: "$DEV:false"
  application:
    modules:
      - fr.imacaron.gif.api.ApplicationKt.module
  deployment:
    port: 8088
    watch:
      - classes
      - resources
db:
  url: $DB_URL
  user: $DB_USER
  password: $DB_PASSWORD